// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEpj9OEJ65qCU9-6OOb0ETXsjhHHJash4',
    appId: '1:1013824412083:web:5c182b55bc6dbe5cde13c6',
    messagingSenderId: '1013824412083',
    projectId: 'spliteasy-88808',
    authDomain: 'spliteasy-88808.firebaseapp.com',
    storageBucket: 'spliteasy-88808.appspot.com',
    measurementId: 'G-6GP78ZETE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKhh0NdJIduOvsX4H7Ezlcky4rePmy1hI',
    appId: '1:1013824412083:android:cd83529d6fa7941ade13c6',
    messagingSenderId: '1013824412083',
    projectId: 'spliteasy-88808',
    storageBucket: 'spliteasy-88808.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByIDiKqKF7IFSEV61VHWMHTInJs7SMbCw',
    appId: '1:1013824412083:ios:48839e5534daba30de13c6',
    messagingSenderId: '1013824412083',
    projectId: 'spliteasy-88808',
    storageBucket: 'spliteasy-88808.appspot.com',
    iosBundleId: 'com.example.spliteasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByIDiKqKF7IFSEV61VHWMHTInJs7SMbCw',
    appId: '1:1013824412083:ios:48839e5534daba30de13c6',
    messagingSenderId: '1013824412083',
    projectId: 'spliteasy-88808',
    storageBucket: 'spliteasy-88808.appspot.com',
    iosBundleId: 'com.example.spliteasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEpj9OEJ65qCU9-6OOb0ETXsjhHHJash4',
    appId: '1:1013824412083:web:f2f8707fc6e2c186de13c6',
    messagingSenderId: '1013824412083',
    projectId: 'spliteasy-88808',
    authDomain: 'spliteasy-88808.firebaseapp.com',
    storageBucket: 'spliteasy-88808.appspot.com',
    measurementId: 'G-6EWVP5PMVJ',
  );
}
